### ISSUE TITLE
Server reporting

### ISSUE THREAD

**Issue by SlimaKCoder** [BlockedServers/tracker#14]
https://help.mojang.com/customer/en/portal/articles/1647288-servers-that-violate-commercial-use-guidelines

**Comment by Chnkr** [comment]
???

**Comment by SlimaKCoder** [comment]
Little offtop, but we can report servers here ;)

**Comment by Chnkr** [comment]
How is that relevant to this project as a whole? This project and especially this repository is here to track changes to the `blockedservers` endpoint on the session server.
